export default function Features() {
  const features = [
    {
      title: "AI-Powered Detection",
      desc: "Detect content generated by GPT-4, Claude, Gemini, and other LLMs with 99.9% accuracy.",
      icon: "🤖"
    },
    {
      title: "Extensive Database",
      desc: "Cross-reference against 100 billion+ web pages, journals, and local repositories.",
      icon: "📚"
    },
    {
      title: "Multilingual Support",
      desc: "Scan documents in English, Hindi, and 50+ other global and regional languages.",
      icon: "🌍"
    },
    {
      title: "Bulk Scanning",
      desc: "Upload and analyze hundreds of documents simultaneously with institutional-grade speed.",
      icon: "⚡"
    }
  ];

  return (
    <section id="features" style={{ padding: '8rem 2rem', background: 'var(--bg-main)' }}>
      <div className="container">
        <div style={{ textAlign: 'center', marginBottom: '5rem' }}>
          <h2 style={{ fontSize: '3.5rem', marginBottom: '1rem', fontWeight: 800 }}>Unparalleled <span className="gradient-text">Features</span></h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.25rem' }}>State-of-the-art tools designed for the modern academic landscape.</p>
        </div>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', 
          gap: '2rem' 
        }}>
          {features.map((f, i) => (
            <div key={i} className="glass-panel hover-lift" style={{ 
              padding: '3rem 2rem',
              textAlign: 'center',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center'
            }}>
              <div className="glow-active" style={{ 
                fontSize: '2.5rem', 
                marginBottom: '2rem',
                background: 'linear-gradient(135deg, hsla(var(--primary-h), var(--primary-s), 50%, 0.1), hsla(var(--accent-h), var(--accent-s), 50%, 0.1))',
                width: '80px',
                height: '80px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                borderRadius: '24px',
                border: '1px solid hsla(var(--primary-h), var(--primary-s), 50%, 0.2)'
              }}>{f.icon}</div>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--text-main)' }}>{f.title}</h3>
              <p style={{ color: 'var(--text-muted)', lineHeight: '1.6' }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
