import { Bot, Library, Globe, Zap } from 'lucide-react';

export default function Features() {
  const features = [
    {
      title: "AI-Powered Detection",
      desc: "Detect content generated by GPT-4, Claude, Gemini, and other LLMs with 99.9% accuracy.",
      icon: <Bot size={28} color="var(--primary)" />
    },
    {
      title: "Extensive Database",
      desc: "Cross-reference against 100 billion+ web pages, journals, and local repositories.",
      icon: <Library size={28} color="var(--primary)" />
    },
    {
      title: "Multilingual Support",
      desc: "Scan documents in English, Hindi, and 50+ other global and regional languages.",
      icon: <Globe size={28} color="var(--primary)" />
    },
    {
      title: "Bulk Scanning",
      desc: "Upload and analyze hundreds of documents simultaneously with institutional-grade speed.",
      icon: <Zap size={28} color="var(--primary)" />
    }
  ];

  return (
    <section id="features" style={{ padding: '8rem 2rem', background: 'transparent' }}>
      <div className="container">
        <div style={{ textAlign: 'center', marginBottom: '5rem' }}>
          <h2 style={{ fontSize: '3rem', marginBottom: '1rem', fontWeight: 700, letterSpacing: '-0.03em' }}>Unparalleled Features</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>State-of-the-art tools designed for the modern academic landscape.</p>
        </div>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', 
          gap: '2rem' 
        }}>
          {features.map((f, i) => (
            <div key={i} className="glass-panel hover-lift" style={{ 
              padding: '3rem 2rem',
              textAlign: 'center',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center'
            }}>
              <div style={{ 
                marginBottom: '1.5rem',
                background: 'transparent',
                width: '60px',
                height: '60px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                borderRadius: '12px',
                border: '1px solid var(--glass-border)'
              }}>{f.icon}</div>
              <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem', color: 'var(--text-main)', fontWeight: 600 }}>{f.title}</h3>
              <p style={{ color: 'var(--text-muted)', lineHeight: '1.5', fontSize: '0.95rem' }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
